/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InfoRouteImport } from './routes/info'
import { Route as MapRouteImport } from './routes/map'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedModerateRouteImport } from './routes/_authenticated/moderate'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as ItemItemIdRouteImport } from './routes/item.$itemId'
import { Route as ReportIndexRouteImport } from './routes/report.index'
import { Route as ReportFoundRouteImport } from './routes/report.found'
import { Route as ReportLostRouteImport } from './routes/report.lost'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModerateRoute = AuthenticatedModerateRouteImport.update({
  id: '/moderate',
  path: '/moderate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFoundRoute = ReportFoundRouteImport.update({
  id: '/report/found',
  path: '/report/found',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportLostRoute = ReportLostRouteImport.update({
  id: '/report/lost',
  path: '/report/lost',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/info': typeof InfoRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/me': typeof AuthenticatedMeRoute
  '/moderate': typeof AuthenticatedModerateRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/report/found': typeof ReportFoundRoute
  '/report/lost': typeof ReportLostRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/info': typeof InfoRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/me': typeof AuthenticatedMeRoute
  '/moderate': typeof AuthenticatedModerateRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/report/found': typeof ReportFoundRoute
  '/report/lost': typeof ReportLostRoute
  '/report': typeof ReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/info': typeof InfoRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/moderate': typeof AuthenticatedModerateRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/report/found': typeof ReportFoundRoute
  '/report/lost': typeof ReportLostRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/info'
    | '/map'
    | '/search'
    | '/me'
    | '/moderate'
    | '/notifications'
    | '/item/$itemId'
    | '/report/found'
    | '/report/lost'
    | '/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/info'
    | '/map'
    | '/search'
    | '/me'
    | '/moderate'
    | '/notifications'
    | '/item/$itemId'
    | '/report/found'
    | '/report/lost'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/info'
    | '/map'
    | '/search'
    | '/_authenticated/me'
    | '/_authenticated/moderate'
    | '/_authenticated/notifications'
    | '/item/$itemId'
    | '/report/found'
    | '/report/lost'
    | '/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InfoRoute: typeof InfoRoute
  MapRoute: typeof MapRoute
  SearchRoute: typeof SearchRoute
  ItemItemIdRoute: typeof ItemItemIdRoute
  ReportFoundRoute: typeof ReportFoundRoute
  ReportLostRoute: typeof ReportLostRoute
  ReportIndexRoute: typeof ReportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderate': {
      id: '/_authenticated/moderate'
      path: '/moderate'
      fullPath: '/moderate'
      preLoaderRoute: typeof AuthenticatedModerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/found': {
      id: '/report/found'
      path: '/report/found'
      fullPath: '/report/found'
      preLoaderRoute: typeof ReportFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/lost': {
      id: '/report/lost'
      path: '/report/lost'
      fullPath: '/report/lost'
      preLoaderRoute: typeof ReportLostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedModerateRoute: typeof AuthenticatedModerateRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedModerateRoute: AuthenticatedModerateRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InfoRoute: InfoRoute,
  MapRoute: MapRoute,
  SearchRoute: SearchRoute,
  ItemItemIdRoute: ItemItemIdRoute,
  ReportFoundRoute: ReportFoundRoute,
  ReportLostRoute: ReportLostRoute,
  ReportIndexRoute: ReportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
